### ISSUE TITLE
11월 5주차 이후

### ISSUE THREAD

**Issue by eumjeongseok** [dlsrks0631/Weather_Seller#11]
이번 Issue 이후로는, 특별한 공지가 없으면 Issue란을 올리지 않습니다.
**팀원 모두가 Issue란을 새로 생성할 수 있으니, 만약 구현상의 어려움이 있다면 New Issue 기능을 사용하시기 바랍니다.**

멘토님과의 회의는 11월 27일 오후 6~9시이며, 비대면(웨일온)입니다.
회의 이후에는 자문보고서를 제출해주시기 바랍니다.
(활동일지는 제가 회의가 끝난 이후 공개하겠습니다. 자체회의는 없습니다.)

추천 알고리즘과 GUI 구현에 대한 결의사항은 11월 4주차를 참고하시기 바랍니다.
모든 내용은 12월 7일 안에 끝내야 합니다. (그래야 캡스톤 예선 준비에 원활한 준비가 가능합니다.)

본래 결과보고서는 12월 1일부터 작성하려고 했으나, 아직 구현 과정이 남아 있어 12월 7일~12월 10일 간에 작성하는 것으로 하겠습니다.
결과보고서는 **저**와 **이수연님**께서 담당할 예정입니다.

12월 1일에는 소프트웨어활용비에 대한 지출 서류만 작성해주시면 됩니다.
지원금 신청은 12월 8일 안에 이루어져야 하기 때문에, 만약 서버 및 인터페이스와 관련하여 지원금을 사용해야 한다면 **반드시 12월 6일 전에 알려주셔야 합니다.** 12/8 이후에 요청하는 지원금에 대해서는 제가 반려하겠습니다.
(이건 SW중심단에서 정한 기한이므로, 제가 바꿀 수 없습니다.)

저 또한 시험으로 많이 바쁘지만, 캡스톤이 무사히 끝나도록 최대한 도와드리겠습니다.
모쪼록 응원합니다. 감사합니다.

**Comment by leesooyeon21** [comment]
제가 추천 시스템 알고리즘을 구현 완료했습니다. 정확도와 결제업종별 백분율을 출력하고 그걸 시각화할 수 있도록 코드를 작성했습니다.  코드를 실행해보시기 바랍니다. 감사합니다.

**Comment by leesooyeon21** [comment]
추가로 네이버 음식점 api 구현은 어떻게 해야 할지 감이 안 잡혀서 아직 구현을 못했습니다. 그리고 제가 이번주까지 중간 대체 레포트를 제출해야 하기 때문에 좀 바쁠 것 같습니다..

**Comment by eumjeongseok** [comment]
api 구현은 11/30일 내로 따로 결정하겠습니다.
일단 추천 알고리즘 결과물이 있다는 것 자체가 대단한 것입니다. :)

**Comment by eumjeongseok** [comment]
제가 최근에 시험 이슈로 조금씩 바빠지고 있습니다.
저도 이제 제출 서류에 대한 일을 끝낸 만큼, GitHub 상황이나 API 관련된 사용법을 익히고자 하지만, 시험 대비로 자주 확인하기는 힘들 것 같습니다.(12.7~12/22까지 기말고사 및 프로젝트 일정)

**1. 만약 결과물이 나온 경우, 기타 자료에 시연 영상 혹은 ppt 설명 자료 추가(기타자료 폴더에 업로드)**
번거롭지만, 여러분들께 부탁합니다.
혹시 최종적으로 API 및 날씨 데이터(weather.csv) 등을 구현한 최종 로직, 서버 인터페이스가 완성되었다면, New issue란이나 이 issue란을 통하여 간단한 시연 영상이나 ppt를 올려주시면 감사하겠습니다.
(그렇지 않으면, 제가 발표자료나 결과보고서를 향후에 담당자와 같이 작성하는데, 코드에 대한 이해가 잘 되지 않아 작성이 힘들어집니다.)
**(그리고, 웬만하면 Github 기타자료에 올려주시기 바랍니다. 번거롭겠지만, 단톡방에 올리시면 파일 찾는 것이 힘들기 때문에 부탁드립니다.)**
API에 대한 사용법 정리는...될 수 있으면 제가 빠른 시일 내에 관련 코드에 Comment란에 올리겠습니다.

**2. 지원금**
그리고, 지원금에 대해서는 다음 주 까지만 받겠습니다.
이왕이면 더 이상은 지원금 신청을 하지 않는 것이 구현에 집중하는 데에는 좋겠지만, 아직 지원금이 많이 남았기에 더 활용할 곳이 있다면 꼭 12/6일 전까지 이야기해주시기 바랍니다. 이후에 지원금 신청서를 작성하는 경우는 안타깝지만 받지 않겠습니다.

**3. 향후 일정**
**-로직 마감: 12/8 자정까지
-서버 및 인터페이스 구현: 12/8 자정까지
-시연 영상: 12/9 자정까지
-결과보고서: 12/21 전까지 (캡스톤 예선 전까지, 제출은 12/22일)**
**-캡스톤 예선: 12월 11일**

*참고로, 로직과 서버/인터페이스는 병렬적으로 수행이 가능합니다.
일단은 시연 영상까지 나오도록 노력해 주시기 바랍니다.


여러모로 저도 캡스톤 프로젝트에 열심히 참여하고 싶은데, 많이 신경을 못 쓴 점 사과드립니다.

**Comment by eumjeongseok** [comment]
12월 7일 18:30~19:30 내부 회의합니다.
방식은 비대면이며, 당일에 회의 링크 공개합니다.

+Issue란은 12/22 정오 이후로 모두 Close하겠습니다.

**Comment by eumjeongseok** [comment]
**최종 내부 회의 방식**

1. 회의 일자: 12/7 18시 30분~19시 30분(공대7호관 무한상상실에서 진행, 대면)
->기본적으로 대면이기 때문에, 비대면으로 하실 분은 미리 이야기해주시기 바랍니다. (이번에는 비대면 회의실을 열지 않습니다. 대면으로 할 생각입니다.)
*삼각대가 있으신 분께서는 가져오시기 바랍니다.
**그리고 회의 중에 갑자기 장소를 이동해야 하는 경우, 그만큼 회의 시간이 지연됩니다.

2. 내용: 구현 이슈 추진, 발표자 및 발표자료 구성
